from decouple import config

MONGODB_URL = config('MONGODB_URL')

JWT_SECRET = config('JWT_SECRET')

GOOGLE_OAUTH_CLIENT_ID = config('GOOGLE_OAUTH_CLIENT_ID')
GOOGLE_OAUTH_CLIENT_SECRET = config('GOOGLE_OAUTH_CLIENT_SECRET')
