version: '3.1'

services:

  web:
    build: .
    restart: always
    ports:
      - '${PORT}:${PORT:-5000}'
    entrypoint:
      - ./bin/entrypoint.sh
    depends_on:
      - redis_db
    environment:
      FRONTEND_URL: ${FRONTEND_URL}
      SERVER_URL: ${SERVER_URL}

      REDIS_TOKENS_DB: ${REDIS_TOKENS_DB:-1}
      REDIS_CASHING_DB: ${REDIS_CASHING_DB:-2}
      REDIS_URL: redis://redis_db:6379

      SEARCH_RESULTS_CACHING_TIME: ${SEARCH_RESULTS_CACHING_TIME:-900}

      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGORITHM: ${JWT_ALGORITHM-:"HS256"}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      REFRESH_TOKEN_EXPIRE_MINUTES: ${REFRESH_TOKEN_EXPIRE_MINUTES:-43200}

      GOOGLE_OAUTH_CLIENT_ID: ${GOOGLE_OAUTH_CLIENT_ID}
      GOOGLE_OAUTH_CLIENT_SECRET: ${GOOGLE_OAUTH_CLIENT_SECRET}
      GOOGLE_BOOKS_API_KEY: ${GOOGLE_BOOKS_API_KEY}
  redis_db:
    image: redis:alpine
    command: redis-server
    environment:
      - REDIS_REPLICATION_MODE=master
